version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: salesforce_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salesforce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  go-app:
    build: .
    container_name: frontlead_go_app
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SF_CONSUMER_KEY=${SF_CONSUMER_KEY}
      - SF_CONSUMER_SECRET=${SF_CONSUMER_SECRET}
      - HS_API_KEY=${HS_API_KEY}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
